export const weatherConditionCode = {
  0: ["Clear sky", "clear"],
  1: ["Mainly clear", "clear"],
  2: ["Partly cloudy", "cloud"],
  3: ["Overcast", "cloud"],
  45: ["Fog", "cloud2"],
  48: ["Depositing rime fog", "cloud-2"],
  51: ["Light drizzle", "rain"],
  53: ["Moderate drizzle", "rain"],
  55: ["Intense drizzle", "rain"],
  61: ["Slight rain", "rain"],
  63: ["Moderate rain", "rain"],
  65: ["Heavy rain", "heavy-rain"],
  66: ["Light freezing rain", "rain"],
  67: ["Heavy freezing rain", "heavy-rain"],
  71: ["Slight snowfall", "snow"],
  73: ["Moderate snowfall", "snow"],
  75: ["Intense snowfall", "snow"],
  77: ["Snow grains", "snow"],
  80: ["Slight rain shower", "heavy-rain"],
  81: ["Moderate rain shower", "heavy-rain"],
  82: ["Violent rain shower", "heavy-rain"],
  85: ["Slight snow shower", "snow"],
  86: ["Heavy snow shower", "snow"],
  95: ["Thunderstorm", "thunderstorm"],
  96: ["Thunderstorm with slight hail", "thunderstorm"],
  99: ["Thunderstorm with heavy hail", "thunderstorm"],
};
